# A script that deploys a Docker image to Google Artifact registry
# and Cloud Run.  Most of the secrets are in Azure App Configuration/Key Vault
# se we log into Azure first to get the secrets.

name: Deploy to Google Cloud Run


on:
  workflow_dispatch:

    
permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    environment: Azure
    
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

    - name: Show Azure Subscription
      run: |
        az account show
        JUBA=$(az appconfig kv show --name arvesv --key "gcr:registry" --query value -o tsv)
        echo "JUBA=$JUBA" >> $GITHUB_ENV
        az appconfig kv list  --auth-mode login --name arvesv --key "gcr:spkey"  --resolve-keyvault --query [].value -o tsv > keyvault.json
        
    - name: Login to Google Cloud
      run: |
        echo ${JUBA} 
        gcloud auth activate-service-account --key-file=keyvault.json
        gcloud info
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://europe-north1-docker.pkg.dev

    - name: Build Docker Image
      run: |
        docker build -t europe-north1-docker.pkg.dev/arvesv/ar/fsweb:latest -f Web/Dockerfile .
        docker push europe-north1-docker.pkg.dev/arvesv/ar/fsweb:latest
      



           
