# A script that deploys a Docker image to Google Cloud Run using GitHub Actions

name: Deploy to Google Cloud Run


on:
  workflow_dispatch:


jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    environment: Azure
    
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
    
    - name: Build the Docker image
      run: docker build . --file Web/Dockerfile
