# A script that deploys a Docker image to Google Artifact registry
# and Cloud Run.  Most of the secrets are in Azure App Configuration/Key Vault
# se we log into Azure first to get the secrets.

name: Deploy to Google Cloud Run


on:
  workflow_dispatch:

    
permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    environment: Azure
    
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_APCONFIG: ${{ secrets.AZURE_APCONFIG }}
      APPNAME: demo1

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login - for app configuration
      # This step logs into Azure to get the App Configuration secrets
      uses: azure/login@v2
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

    - name: Get App Configuration
      run: |
        MYCONFIG=$(az appconfig kv list  --auth-mode login --name ${{secrets.AZURE_APPCONFIG}} --resolve-keyvault --key "${APPNAME}:*")   
        echo "MYCONFIG=$MYCONFIG"     
        REGISTRY=$(echo $MYCONFIG | jq -r '.[] | select(.key == "${APPNAME}:registry") | .value')
        echo $REGISTRY
        SPKEY=$(echo $MYCONFIG | jq -r '.[] | select(.key == "${APPNAME}:spkey") | .value')

    - name: Login to Google Cloud
      run: |
        echo $SPKEY
        echo $SPKEY | gcloud auth activate-service-account --key-file=-
        cloud info





           
