# A script that deploys a Docker image to Google Artifact registry
# and Cloud Run.  Most of the secrets are in Azure App Configuration/Key Vault
# se we log into Azure first to get the secrets.

name: Deploy to Google Cloud Run


on:
  workflow_dispatch:


jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    environment: Azure
    
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
    - uses: actions/checkout@v4

    - name: Test
      run: env

