# A script that deploys a Docker image to Google Cloud Run using GitHub Actions

name: Deploy to Google Cloud Run


on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
