name: Test GitHub Actions Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
   
      - name: Run tool setup
        run: |
          JSONX='{"name": "test", "version": "1.0.0"}'
          JUBA=$(echo $JSONX | jq '.name')
          echo "JUBA: $JUBA"
          jq -V
