name: Test GitHub Actions Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

        
permissions:
  id-token: write
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    environment: Azure

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_APPCONFIG: ${{ secrets.AZURE_APPCONFIG }}
      APPNAME: demo1

    steps:
      - uses: actions/checkout@v4
   
      - name: Azure Login
      # This step logs into Azure to get the App Configuration settings
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}


      - name: Do JSON manipulation
        run: |
          MYCONFIG=$(az appconfig kv list  --auth-mode login --name $AZURE_APPCONFIG  --resolve-keyvault --key "${APPNAME}:*")  
          echo "MYCONFIG: $MYCONFIG"
          JSONX='{"name": "test", "version": "1.0.0"}'
          JUBA=$(echo $JSONX | jq '.name')
          echo "JUBA: $JUBA"
          echo "JUBA=$JUBA" >> $GITHUB_ENV
          jq -V

      - name: new steo
        run: |
          echo "This is a new step in the workflow"
          echo "Current date and time: $(date)"
          echo "Running on $(uname -a)"
          echo "JUBA from previous step: $JUBA"
